version: '3.8'

services:
  postgres:
    image: postgres:16

    container_name: progressor-db

    environment:
      POSTGRES_USER: progressoruser
      POSTGRES_PASSWORD: progressorpass
      POSTGRES_DB: progressordb

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: