-- Flyway Migration: V1
-- Description: Creates all initial tables for the ProgressorAPI project.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at DATE NOT NULL
);

CREATE TABLE exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    muscle_group VARCHAR(50)
);

CREATE TABLE workouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(100),
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    CONSTRAINT fk_workouts_users FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE workout_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    reps INT,
    weight_kg DOUBLE PRECISION,
    duration_seconds INT,
    CONSTRAINT fk_workout_sets_workouts FOREIGN KEY (workout_id) REFERENCES workouts(id),
    CONSTRAINT fk_workout_sets_exercises FOREIGN KEY (exercise_id) REFERENCES exercises(id)
);

CREATE TABLE body_measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    measurement_date DATE NOT NULL,
    weight_kg DOUBLE PRECISION,
    body_fat_percentage DOUBLE PRECISION,
    chest DOUBLE PRECISION,
    abdomen DOUBLE PRECISION,
    waist DOUBLE PRECISION,
    hips DOUBLE PRECISION,
    right_arm DOUBLE PRECISION,
    left_arm DOUBLE PRECISION,
    right_thigh DOUBLE PRECISION,
    left_thigh DOUBLE PRECISION,
    right_calf DOUBLE PRECISION,
    left_calf DOUBLE PRECISION,
    CONSTRAINT fk_body_measurements_users FOREIGN KEY (user_id) REFERENCES users(id)
);